# Generated by Django 2.2.5 on 2020-09-12 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
