# Generated by Django 2.2.5 on 2020-09-24 09:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200913_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='createdTime',
        ),
        migrations.AddField(
            model_name='post',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
    ]
