# Generated by Django 2.2.5 on 2020-09-29 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20200925_2148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_time', 'name'], 'verbose_name': '评论', 'verbose_name_plural': '评论'},
        ),
    ]
